config/routes.rb
Rails.application.routes.draw do
  # 会員用サインアップ・ログイン用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲスト用ログイン機能
  devise_scope :end_user do
    post "end_user/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "search" => "searches#search"
    resources :categories, only: [:show]
    resources :personal_tags, only: [:show]
    resources :tags, only: [:show]
    resources :notifications, only: [:index]

    # ユーザー関連
    resources "end_users", only: [:index, :show, :edit, :update] do
      resource "relationships", only: [:create, :destroy]
      get :following, on: :member
      get :follower, on: :member
      get :unsubscribe, on: :member
      patch :withdraw, on: :member
    end

    # コミュニティ関連
    resources "communities", except: [:destroy] do
      get :member, on: :member
      get :question, on: :member
      post :invitation
      resources "community_messages", only: [:new, :create, :destroy]
      resource "community_users", only: [:create, :destroy] do
        delete :evict
      end
      # トピック関連
      resources "topics", except: [:destroy] do
        resource "bookmarks", only: [:create, :destroy]
        resources "topic_comments", only: [:create, :destroy] do
          resource "goods", only: [:create, :destroy]
        end
      end
    end
  end

  # 管理者用サインアップ用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "homes/top", as: "home"
    get "topics/topic_list", as: "topics"
    get "topic_comments/topic_comment_list", as: "topic_comments"
    get "search" => "searches#search"
    resources "end_users", only: [:show, :edit, :update]
    resources "communities", only: [:index, :show, :edit, :update, :destroy] do
      get :member, on: :member
      get :question, on: :member
      resource "community_users", only: [:destroy]
      resources "community_messages", only: [:destroy]
      resources "topics", only: [:index, :show, :edit, :update, :destroy] do
        resources "topic_comments", only: [:update, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_one_attached :topic_image_1
  has_one_attached :topic_image_2
  has_one_attached :topic_image_3
  belongs_to :end_user
  belongs_to :community
  has_many :topic_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true, length: { maximum: 600 }

  # ブックマークされているかの判定メソッド
  def bookmarked_by?(user)
    bookmarks.exists?(end_user_id: user.id)
  end

  def self.search_for(content)
    Topic.where("title Like?", "%#{content}%")
  end

  # コメント返信時の通知メソッド ※トピックメンバー全員（通知を作成）
  def comment_reply_notification(current_end_user, comment_id)
    temp_ids = TopicComment.where(topic_id: id).where.not(end_user_id: current_end_user.id).distinct.pluck(:end_user_id)
    # コメントされていない場合は、トピック投稿者に通知を送る
    if temp_ids.blank?
      notification = current_end_user.active_notifications.new(topic_id: id, topic_comment_id: comment_id, visited_id: end_user_id, action: "comment")
      notification.save if notification.valid?
    # コメントされている場合は、コメント欄のメンバーに通知を送る
    else
      temp_ids.each do |temp_id|
        notification = current_end_user.active_notifications.new(topic_id: id, topic_comment_id: comment_id, visited_id: temp_id, action: "comment")
        if notification.visitor_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
      end
    end
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_community, except: [:topic_list, :update]
  before_action :find_topic, only: [:show, :edit, :update, :destroy]

  def topic_list
    @topics = Topic.all.order(id: "DESC").page(params[:page]).per(20)
  end

  def index
    @topics = Topic.where(community_id: params[:community_id]).order(id: "DESC").page(params[:page]).per(10)
  end

  def show
    @topic_comment = TopicComment.new
    @topic_comments = @topic.topic_comments
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to admin_community_topic_path(@topic.community_id, @topic), notice: "更新が完了しました！"
    else
      flash.now[:alert] = "更新に失敗しました"
      render edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to admin_topics_path, notice: "削除が完了しました！"
  end

  private
    def topic_params
      params.require(:topic).permit(:title, :body, :topic_image_1, :topic_image_2, :topic_image_3)
    end

    def find_community
      @community = Community.find(params[:community_id])
    end

    def find_topic
      @topic = Topic.find(params[:id])
    end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/views/admin/topics/_list.html.erb
<% topics.each do |topic| %>
  <tr>
    <td><%= topic.id %></td>
    <td><%= topic.title.truncate(20) %></td>
    <td><%= link_to topic.end_user.nickname, admin_end_user_path(topic.end_user) %></td>
    <td><%= topic.created_at.strftime("%Y/%m/%d\ %R") %></td>
    <td><%= link_to "#{topic.community.name}", admin_community_path(topic.community) %></td>
    <td><%= link_to "詳細", admin_community_topic_path(topic.community_id, topic), class: "btn btn-primary btn-sm" %></td>
  </tr>
<% end %>

app/views/admin/topics/edit.html.erb
<div class="container py-5">
  <div class="row m-4">
    <h3><i class="fas fa-pen"></i>&nbsp;トピック編集</h3>
  </div>
  <%= form_with model:[@community, @topic], url: admin_community_topic_path(@topic.community_id, @topic), method: :patch do |f| %>
    <div class="form-group row was-validated">
      <div class="col-lg-2">
        <%= f.label :title,'トピック名', class:"col-form-label" %>
        <small><span class="badge badge-danger ml-2">必須</span></small>
      </div>
      <div class="col-lg-10">
        <%= f.text_field :title, required:true, class: 'form-control' %>
        <div class="invalid-feedback">入力されていません</div>
      </div>
    </div>
    <div class="form-group row was-validated">
      <div class="col-lg-2">
        <%= f.label :body, '本文', class:"col-form-label" %>
        <small><span class="badge badge-danger ml-2">必須</span></small>
      </div>
      <div class="col-lg-10">
        <%= f.text_area :body, required:true, rows:"8", class: "form-control" %>
        <div class="invalid-feedback">入力されていません</div>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-lg-2">
        <%= f.label :topic_image,'投稿画像', class:"col-form-label" %><br>
        <small>※３つまで投稿可</small>
      </div>
      <div class="col-lg-10">
        <div class="row mx-0 justify-content-center">
          <div class="col-md-4 col-12 text-center">
            <label>
              <span class="text-primary">
                <i class="fas fa-camera"></i>&nbsp;画像を選択する
                <%= f.file_field :topic_image_1, accept:'image/*', style:"display:none", id:"input-file_1" %>
              </span>
            </label>
            <div>
              <% if @topic.topic_image_1.present? %>
                <%= image_tag @topic.topic_image_1, size: "250x250", class:"img-thumbnail", id:'preview_1' %>
              <% else %>
                <%= image_tag asset_path('no_image.jpg'), size: "250x250", class:"img-thumbnail", id:'preview_1' %>
              <% end %>
            </div>
          </div>
          <div class="col-md-4 col-12 text-center">
            <label>
              <span class="text-primary">
                <i class="fas fa-camera"></i>&nbsp;画像を選択する
                <%= f.file_field :topic_image_2, accept:'image/*', style:"display:none", id:"input-file_2" %>
              </span>
            </label>
            <div>
              <% if @topic.topic_image_2.present? %>
                <%= image_tag @topic.topic_image_2, size: "250x250", class:"img-thumbnail", id:'preview_2' %>
              <% else %>
                <%= image_tag asset_path('no_image.jpg'), size: "250x250", class:"img-thumbnail", id:'preview_2' %>
              <% end %>
            </div>
          </div>
          <div class="col-md-4 col-12 text-center">
            <label>
              <span class="text-primary">
                <i class="fas fa-camera"></i>&nbsp;画像を選択する
                <%= f.file_field :topic_image_1, accept:'image/*', style:"display:none", id:"input-file_3" %>
              </span>
            </label>
            <div>
              <% if @topic.topic_image_3.present? %>
                <%= image_tag @topic.topic_image_3, size: "250x250", class:"img-thumbnail", id:'preview_3' %>
              <% else %>
                <%= image_tag asset_path('no_image.jpg'), size: "250x250", class:"img-thumbnail", id:'preview_3' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="form-group row justify-content-center">
      <%= f.submit class: 'btn btn-info mt-5', style:"width: 30%" %>
    </div>
  <% end %>
</div>

app/views/admin/topics/index.html.erb
<div class="container py-5">
  <div class="row m-4">
    <h3><i class="fas fa-list"></i>&nbsp;トピック一覧</h3>
  </div>
  <div class="mt-3">
    <%= render 'admin/communities/member', community: @community %>
  </div>
  <div class="row mx-1">
    <div class="col-12">
      <ul class="list-group">
        <% @topics.each do |topic| %>
          <li class="list-group-item p-3">
            <div class="row mx-2">
              <%= link_to admin_end_user_path(topic.end_user) do %>
                <%= image_tag topic.end_user.get_profile_image(40, 40), class: "img-thumbnail rounded-circle mr-2" %>
              <% end %>
              <div>
                <small class="text-info"><%= topic.end_user.nickname %></small><br>
                <small><%= topic.created_at.strftime("%Y/%m/%d\ %R") %></small>
              </div>
            </div>
            <div class="m-3">
              <% if topic.end_user.active_for_authentication? %>
                <h5 class="mt-2"><%= link_to topic.title.truncate(35), admin_community_topic_path(topic.community, topic) %></h5>
                <p><%= topic.body.truncate(100) %></p>
              <% else %>
                <h5 class="mt-2"><%= link_to topic.title.truncate(35), admin_community_topic_path(topic.community, topic) %></h5>
                <p><%= topic.body.truncate(100) %></p>
                <small>※このトピックは、投稿したユーザーアカウントが利用停止中です</small>
              <% end %>
            </div>
            <div class="row justify-content-end">
              <small class="mr-2"><%= link_to topic.community.name, admin_community_path(topic.community) %></small>
              <small class="mx-2"><span><i class="far fa-heart"></i>&nbsp;<%= topic.bookmarks.count %></span></small>
              <small class="mx-2"><%= "#{topic.topic_comments.count}" + "コメント" %></small>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= paginate @topics %>
</div>

app/views/admin/topics/show.html.erb
<div class="container py-5">
  <div class="row m-4">
    <h3><i class="fas fa-info"></i>&nbsp;トピック詳細</h3>
  </div>
  <div class="row justify-content-around">
    <div class="col-md-2 text-center mb-2">
      <%= link_to admin_end_user_path(@topic.end_user) do %>
        <%= image_tag @topic.end_user.get_profile_image(250, 250), class:"img-thumbnail mb-2" %>
        <h6 class="text-info"><%= @topic.end_user.nickname %></h6>
      <% end %>
      <div class="text-center">
        <%= link_to '編集する', edit_admin_community_topic_path(@topic.community, @topic), class: "btn btn-sm btn-info mt-2", style:"width: 100%" %>
        <%= link_to '削除する', admin_community_topic_path(@topic.community, @topic), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-sm btn-danger mt-2", style:"width: 100%" %>
      </div>
    </div>
    <div class="col-md-9 bg-white rounded-lg border shadow mx-2 p-3">
      <div class="col-12">
        <p>投稿日：<%= @topic.created_at.strftime("%Y/%m/%d\ %R") %></p>
        <h3 class="font-weight-bold"><%= @topic.title %></h3>
        <div class="border-top border-info"></div>
      </div>
      <div class="col-12 p-3">
        <h6><%= safe_join(@topic.body .split("\n"), tag(:br)) %></h6>
      </div>
      <div class="row mx-0">
        <div class="col-sm-4 col-12 text-center p-2">
          <%= image_tag @topic.topic_image_1.variant(resize_to_fill:[310, 310]).processed, class:"img-fluid" if @topic.topic_image_1.present? %>
        </div>
        <div class="col-sm-4 col-12 text-center p-2">
          <%= image_tag @topic.topic_image_2.variant(resize_to_fill:[310, 310]).processed, class:"img-fluid" if @topic.topic_image_2.present?%>
        </div>
        <div class="col-sm-4 col-12 text-center p-2">
          <%= image_tag @topic.topic_image_3.variant(resize_to_fill:[310, 310]).processed, class:"img-fluid" if @topic.topic_image_3.present?%>
        </div>
      </div>
      <div class="row justify-content-end mx-2">
        <small class="mx-2"><%= link_to 'トピック一覧へ', admin_community_topics_path(@topic.community) %></small>
        <small class="mx-2"><i class="far fa-heart"></i>&nbsp;<%= @topic.bookmarks.count %></small>
        <small class="mx-2"><%= "#{@topic.topic_comments.count}" + "コメント" %></small>
      </div>
    </div>
  </div>
  <div class="row justify-content-center my-4">
    <div class="topic-comments-index col-md-11 col-12">
      <%= render 'admin/topic_comments/index', topic_comments: @topic_comments %>
    </div>
  </div>
</div>

app/views/admin/topics/top.html.erb
<div class="container">
  <div class="row m-4">
    <h2>トピックス一覧</h2>
  </div>

  <div class="row">
    <table class="table">
      <thead class="thead-light">
        <th>ID</th>
        <th>タイトル</th>
        <th>投稿者</th>
        <th>投稿日</th>
        <th>コミュニティ名</th>
        <th></th>
      </thead>
      <tbody>
        <% @topics.each do |topic| %>
          <tr>
            <td><%= topic.id %></td>
            <td><%= topic.title.truncate(25) %></td>
            <td><%= link_to "#{topic.end_user.last_name + topic.end_user.first_name}", admin_end_user_path(topic.end_user) %></td>
            <td><%= topic.created_at.strftime("%Y/%m/%d\ %R") %></td>
            <td><%= link_to "#{topic.community.name}", admin_community_path(topic.community) %></td>
            <td><%= link_to "詳細", admin_community_topic_path(topic.community_id, topic), class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>

</div>

app/views/admin/topics/topic_list.html.erb
<div class="container py-5">
  <div class="row justify-content-end">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <%= render 'admin/searches/form' %>
    </div>
  </div>
  <div class="row m-4">
    <h3>トピックス一覧</h3>
  </div>
  <div class="table-responsive-xl">
    <table class="table text-nowrap">
      <thead class="thead-light">
        <th>TopicID</th>
        <th>タイトル</th>
        <th>投稿者</th>
        <th>投稿日</th>
        <th>コミュニティ名</th>
        <th></th>
      </thead>
      <tbody>
        <%= render 'admin/topics/list', topics: @topics %>
      </tbody>
    </table>
  </div>
  <%= paginate @topics %>
</div>