config/routes.rb
Rails.application.routes.draw do
  # 会員用サインアップ・ログイン用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲスト用ログイン機能
  devise_scope :end_user do
    post "end_user/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "search" => "searches#search"
    resources :categories, only: [:show]
    resources :personal_tags, only: [:show]
    resources :tags, only: [:show]
    resources :notifications, only: [:index]

    # ユーザー関連
    resources "end_users", only: [:index, :show, :edit, :update] do
      resource "relationships", only: [:create, :destroy]
      get :following, on: :member
      get :follower, on: :member
      get :unsubscribe, on: :member
      patch :withdraw, on: :member
    end

    # コミュニティ関連
    resources "communities", except: [:destroy] do
      get :member, on: :member
      get :question, on: :member
      post :invitation
      resources "community_messages", only: [:new, :create, :destroy]
      resource "community_users", only: [:create, :destroy] do
        delete :evict
      end
      # トピック関連
      resources "topics", except: [:destroy] do
        resource "bookmarks", only: [:create, :destroy]
        resources "topic_comments", only: [:create, :destroy] do
          resource "goods", only: [:create, :destroy]
        end
      end
    end
  end

  # 管理者用サインアップ用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "homes/top", as: "home"
    get "topics/topic_list", as: "topics"
    get "topic_comments/topic_comment_list", as: "topic_comments"
    get "search" => "searches#search"
    resources "end_users", only: [:show, :edit, :update]
    resources "communities", only: [:index, :show, :edit, :update, :destroy] do
      get :member, on: :member
      get :question, on: :member
      resource "community_users", only: [:destroy]
      resources "community_messages", only: [:destroy]
      resources "topics", only: [:index, :show, :edit, :update, :destroy] do
        resources "topic_comments", only: [:update, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/community.rb
class Community < ApplicationRecord
  has_one_attached :community_image
  has_many :community_users, dependent: :destroy
  has_many :end_users, through: :community_users
  belongs_to :owner, class_name: "EndUser"
  has_many :community_messages, dependent: :destroy
  has_one :community_detail, dependent: :destroy
  accepts_nested_attributes_for :community_detail
  has_many :community_tags, dependent: :destroy
  has_many :tags, through: :community_tags
  has_many :topics, dependent: :destroy
  has_many :topic_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  belongs_to :category, optional: true

  validates :name, presence: true, length: { maximum: 50 }
  validates :introduction, presence: true, length: { maximum: 600 }

  def get_community_image(width, height)
    unless community_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      community_image.attach(io: File.open(file_path), filename: "no-image.jpg", content_type: "image/jpeg")
    end
    community_image.variant(resize_to_fill: [width, height]).processed
  end

  # トピックが投稿された順でのコミュニティ情報を取得
  def self.lasted_post_community_get
    Community.find(Topic.order(created_at: :desc).pluck(:community_id))
  end

  # カテゴリー情報の保存メソッド
  def save_category(category_name)
    unless category_name == []
      category = Category.find_or_create_by(name: category_name)
      self.update(category_id: category.id)
    end
  end

  # タグ情報の保存メソッド
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end
    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name: new_name)
      self.tags << post_tag
    end
  end

  def self.search_for(content)
    Community.where("name Like?", "%#{content}%")
  end

  # コミュニティに参加済みかの確認メソッド
  def already_joined?(end_user)
    community_users.exists?(end_user_id: end_user.id)
  end

  # コミュニティへの招待通知メソッド（通知を作成）
  def community_invitation_notification(current_end_user, visited_id)
    temp = Notification.where(visited_id: visited_id, community_id: id, action: "invitation")
    if temp.blank?
      notification = current_end_user.active_notifications.new(visited_id: visited_id, community_id: id, action: "invitation")
      notification.save if notification.valid?
    end
  end

  # コミュニティへの参加通知メソッド ※メンバー全員（通知を作成）
  def community_join_notification(current_end_user)
    temp_ids = CommunityUser.where(community_id: id).where.not(end_user_id: current_end_user.id).pluck(:end_user_id)
    temp_ids.each do |temp_id|
      notification = current_end_user.active_notifications.new(visited_id: temp_id, community_id: id, action: "join")
      notification.save if notification.valid?
    end
  end

  # トピック作成時の投稿通知メソッド ※メンバー全員（通知を作成）
  def topic_post_notification(current_end_user, topic_id)
    temp_ids = CommunityUser.where(community_id: id).where.not(end_user_id: current_end_user.id).pluck(:end_user_id)
    temp_ids.each do |temp_id|
      notification = current_end_user.active_notifications.new(visited_id: temp_id, community_id: id, topic_id: topic_id, action: "post")
      notification.save if notification.valid?
    end
  end

  paginates_per 8
end

app/controllers/admin/communities_controller.rb
class Admin::CommunitiesController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_community, except: [:index]

  def index
    @communities = Community.all.order(id: "DESC").page(params[:page]).per(20)
  end

  def show
    @topics = @community.topics.order(id: "DESC").limit(10)
  end

  def edit
    @tag_list = @community.tags.pluck(:name).join(" ")
  end

  def update
    tag_list = params[:community][:community_tag_name].split(nil)
    if (params[:community][:community_detail_attributes][:age_max_limit] == "") || (params[:community][:community_detail_attributes][:age_min_limit] <= params[:community][:community_detail_attributes][:age_max_limit])
      if @community.update(community_params)
        @community.save_tag(tag_list)
        redirect_to admin_community_path, notice: "更新完了しました！"
      else
        flash.now[:alert] = "更新に失敗しました"
        render "edit"
      end
    else
      flash.now[:alert] = "最少年齢設定が最大年齢設定を上回っています"
      render "edit"
    end
  end

  def destroy
    @community.destroy
    redirect_to admin_communities_path, notice: "削除が完了しました！"
  end

  def member
    @members = CommunityUser.where(community_id: @community.id)
  end

  def question
  end

  private
    def community_params
      params.require(:community).permit(:name, :introduction, :community_image, community_detail_attributes: [:max_join_number, :sex_limit, :activity_area_limit, :age_min_limit, :age_max_limit, :recruiting_status, :_destroy, :id])
    end

    def find_community
      @community = Community.find(params[:id])
    end
end

app/helpers/admin/communities_helper.rb
module Admin::CommunitiesHelper
end

app/views/admin/communities/_list.html.erb
<% communities.each do |community| %>
  <tr>
    <td><%= community.id %></td>
    <td><%= community.name %></td>
    <td><%= link_to community.owner.nickname, admin_end_user_path(community.owner) %></td>
    <td><span class="h5 text-danger"><%= community.end_users.count %></span>人が参加</span></td>
    <td>
      <% detail = community.community_detail %>
      <%= render 'admin/community_details/community_detail', detail: detail %>
    </td>
    <td><%= detail.recruiting_status_i18n %></td>
    <td><%= link_to "詳細", admin_community_path(community), class: "btn btn-primary btn-sm" %></td>
  </tr>
<% end %>

app/views/admin/communities/_member.html.erb
<div class="d-flex justify-content-between">
  <span>メンバー：<span class="h5 text-danger"><%= community.end_users.count %></span>人が参加中</span>
  <%= link_to 'もっと見る >>', member_admin_community_path(community) %>
</div>
<div class="row flex-nowrap overflow-auto mt-2">
  <div class="text-center" style="min-width: 150px">
    <h6><span class="badge badge-info">リーダー</span></h6>
    <%= link_to admin_end_user_path(community.owner) do %>
      <%= image_tag community.owner.get_profile_image(60, 60), class:"img-thumbnail rounded-circle" %>
      <p class="text-info"><small><%= community.owner.nickname %></small></p>
    <% end %>
  </div>
  <div>
    <h6><span class="badge badge-secondary">その他メンバー</span></h6>
    <div class="row flex-nowrap text-center">
      <% community.end_users.each do |member| %>
        <% unless !member.active_for_authentication? || community.owner == member %>
          <div style="width: 100px">
            <%= link_to admin_end_user_path(member) do %>
              <%= image_tag member.get_profile_image(60, 60), class:"img-thumbnail rounded-circle" %>
              <p class="text-info"><small><%= member.nickname %></small></p>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/communities/_member_list_type.html.erb
<ul class="list-group bg-white">
  <li class="media border p-3">
    <div class='text-center mr-3'>
      <%= link_to admin_end_user_path(community.owner_id) do %>
        <%= image_tag community.owner.get_profile_image(80, 80), class:"d-block img-thumbnail" %>
      <% end %>
    </div>
    <div class="media-body">
      <h5><%= community.owner.nickname %><span class="badge badge-info ml-3">リーダー</span></h5>
      <p><%= community.owner.introduction.truncate(100) %></p>
      <% community.owner.personal_tags.each do |tag| %>
        <small class="mr-2"><%= link_to "#" + tag.name, personal_tag_path(tag), class:"text-secondary" %></small>
      <% end %>
    </div>
  </li>
  <% members.each do |member| %>
    <% unless !member.end_user.active_for_authentication? || community.owner == member.end_user %>
      <li class="media border p-3">
        <div class='text-center mr-3'>
          <%= link_to admin_end_user_path(member.end_user.id) do %>
            <%= image_tag member.end_user.get_profile_image(80, 80), class:"d-block img-thumbnail" %>
          <% end %>
          <%= link_to '退出', admin_community_community_users_path(community, user_id: member.end_user.id), method: :delete, data: {confirm: "本当にこのメンバーを退出させますか？"}, class:"btn btn-secondary btn-sm", style:"width: 85px" %>
        </div>
        <div class="media-body">
          <h5><%= member.end_user.nickname %></h5>
          <p><%= member.end_user.introduction.truncate(100) %></p>
          <% member.end_user.personal_tags.each do |tag| %>
            <small class="text-secondary mr-2"><%= "#" + tag.name %></small>
          <% end %><br>
          <small class=""><%= "加入日：#{member.created_at.strftime("%Y/%m/%d")}" %></small>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/admin/communities/edit.html.erb
<div class="container py-5">
  <div class="row m-4">
    <h3><i class="fas fa-pen"></i>&nbsp;コミュニティ編集</h3>
  </div>
  <%= form_with model:@community, url: admin_community_path(@community), method: :patch do |f| %>
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="text-center">
          <div><%= image_tag @community.community_image, size: "400x400", class:"img-thumbnail", id:'preview' %></div>
          <label>
            <span class="text-primary">
              <i class="fas fa-camera"></i>&nbsp;画像を選択する
              <%= f.file_field :community_image, accept:'image/*', style:"display:none", id:"input-file" %>
            </span>
          </label>
        </div>
      </div>
    </div>
    <div class="form-group row was-validated">
      <div class="col-lg-2 col-md-3 col-sm-4">
        <%= f.label :name,'コミュ名', class:"col-form-label" %>
        <small><span class="badge badge-danger ml-2">必須</span></small>
      </div>
      <div class="col-md-9">
        <%= f.text_field :name, required:true, class: 'form-control' %>
        <div class="invalid-feedback">入力されていません</div>
      </div>
    </div>
    <div class="form-group row was-validated">
      <div class="col-lg-2 col-md-3 col-sm-4">
        <%= f.label :introduction, '紹介文', class:"col-form-label" %>
        <small><span class="badge badge-danger ml-2">必須</span></small>
      </div>
      <div class="col-md-9">
        <%= f.text_area :introduction, rows:"5", required:true, class: 'form-control' %>
        <div class="invalid-feedback">入力されていません</div>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :community_tag_name, 'タグ', class:"col-lg-2 col-md-3 col-sm-4" %>
      <div class="col-md-8">
        <%= f.text_field :community_tag_name, value: @tag_list, class: "form-control" %>
        <small> ※半角スペースを入力することで、複数のタグを付けることができます</small>
      </div>
    </div>
    <%= f.fields_for :community_detail do |i| %>
      <div class="form-group row">
        <%= i.label :max_join_number, '参加上限人数', class:"col-lg-2 col-md-3 col-sm-4 col-form-label" %>
        <div class="col-md-4 col-sm-5">
          <%= i.select :max_join_number, (2..100).to_a, {include_blank: "設定しない"}, class:"form-control" %>
        </div>
        &nbsp;<span class="col-form-label pl-3">人まで</span>
      </div>
      <div class="form-group row">
        <%= i.label :sex_limit, '性別制限', class:"col-lg-2 col-md-3 col-sm-4 col-form-label" %>
        <div class="col-md-4 col-sm-5">
          <%= i.select :sex_limit, CommunityDetail.sex_limits_i18n.invert, {include_blank: "設定しない"}, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= i.label :activity_area_limit, '活動エリア制限', class:"col-lg-2 col-md-3 col-sm-4 col-form-label" %>
        <div class="col-md-4 col-sm-5">
          <%= i.select :activity_area_limit, CommunityDetail.activity_area_limits_i18n.invert, {include_blank: "設定しない"}, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= i.label :age_min_limit, '年齢制限（最少）', class:"col-lg-2 col-md-3 col-sm-4 col-form-label" %>
        <div class="col-lg-2 col-md-3 col-sm-5">
          <%= i.select :age_min_limit, (18..99).to_a, {include_blank: "設定しない"}, class:"d-inline form-control" %>
        </div>
        &nbsp;<span class="col-form-label pl-3">〜</span>
        <%= i.label :age_max_limit, '（最大）', class:"col-xl-1 col-md-2 col-sm-4 col-form-label" %>
        <div class="col-lg-2 col-md-3 col-sm-5 ">
          <%= i.select :age_max_limit, (18..99).to_a, {include_blank: "設定しない"}, class:"d-inline form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <%= i.label :recruiting_status, '募集ステータス', class:"col-lg-2 col-md-3 col-sm-4 col-form-label" %>
        <div class="col-md-9 col-sm-8">
          <%= i.radio_button :recruiting_status, CommunityDetail.recruiting_statuses.key(0)%>
          <%= i.label :recruiting_status_recruting, CommunityDetail.recruiting_statuses_i18n[:recruiting], class:"col-form-label mr-5" %>
          <%= i.radio_button :recruiting_status, CommunityDetail.recruiting_statuses.key(1) %>
          <%= i.label :recruiting_status_recruting, CommunityDetail.recruiting_statuses_i18n[:closed], class:"col-form-label" %>
        </div>
      </div>
    <% end %>
    <div class="form-group row justify-content-center">
      <%= f.submit class: 'btn btn-info mt-5 mx-3', style:"width: 25%" %>
    </div>
  <% end %>
</div>

app/views/admin/communities/index.html.erb
<div class="container py-5">
  <div class="row justify-content-end">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <%= render 'admin/searches/form' %>
    </div>
  </div>
  <div class="row m-4">
    <h3>コミュニティ一覧</h3>
  </div>
  <div class="table-responsive-md">
    <table class="table text-nowrap">
      <thead class="thead-light">
        <th>ComuID</th>
        <th>コミュニティ名</th>
        <th>作成者</th>
        <th>メンバー</th>
        <th>参加条件設定</th>
        <th>募集状況</th>
        <th></th>
      </thead>
      <tbody>
        <%= render 'admin/communities/list', communities: @communities %>
      </tbody>
    </table>
  </div>
  <%= paginate @communities %>
</div>

app/views/admin/communities/member.html.erb
<div class="container py-5">
  <div class="row m-4">
    <h3><i class="fas fa-users"></i>「<%= @community.name %>」の参加メンバー</h3>
  </div>
    <div>
      <%= render 'admin/communities/member_list_type', members: @members, community: @community %>
    </div>
</div>

app/views/admin/communities/question.html.erb
<div class="container py-5">
  <div class="row justify-content-center my-4">
    <div class="message-index col-md-11 col-12">
      <ul class="list-group">
        <% @community.community_messages.each do |message| %>
          <% unless message.parent_id %>
            <li class="list-group-item p-3">
              <div class="row mx-2">
                <%= link_to admin_end_user_path(message.end_user) do %>
                  <%= image_tag message.end_user.get_profile_image(40, 40), class:"img-thumbnail rounded-circle mr-2" %>
                <% end %>
                <div>
                  <span class="text-info"><%= message.end_user.nickname %></span>
                  <% if message.community.owner == message.end_user %>
                    <span class="badge badge-info ml-3">リーダー</span>
                  <% end %><br>
                  <small><%= message.created_at.strftime("%Y/%m/%d\ %R") %></small>
                </div>
              </div>
              <div class="ml-4 my-3"><%= message.message %></div>
              <div class="row justify-content-end">
                <%= link_to '削除', admin_community_community_message_path(message.community, message), method: :delete, data: {confirm: "コメントを削除しますか？"}, class:"btn btn-sm btn-danger mr-3" %>
              </div>
              <% if message.replies.any? %>
                <% message.replies.each do |reply| %>
                  <div class="ml-5">
                    <div class="row mx-0">
                      <%= link_to admin_end_user_path(reply.end_user) do %>
                        <%= image_tag reply.end_user.get_profile_image(40, 40), class:"img-thumbnail rounded-circle mr-2" %>
                      <% end %>
                      <div>
                        <span class="text-info"><%= reply.end_user.nickname %></span>
                        <% if message.community.owner == reply.end_user %>
                          <span class="badge badge-info ml-3">リーダー</span>
                        <% end %><br>
                        <small><%= reply.created_at.strftime("%Y/%m/%d\ %R") %></small>
                      </div>
                    </div>
                    <div class="ml-4 my-3"><%= reply.message %></div>
                    <div class="row justify-content-end">
                      <%= link_to '削除', admin_community_community_message_path(reply.community, reply), method: :delete, data: {confirm: "コメントを削除しますか？"}, class:"btn btn-sm btn-danger mr-3" %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/admin/communities/show.html.erb
<div class="container py-5">
  <div class="row m-4">
    <h3><i class="fas fa-object-group"></i>「<%= @community.name %>」のコミュニティ詳細</h3>
  </div>
  <div class="row justify-content-around">
    <div class="col-lg-12 col-md-10 col-12">
      <div class="card shadow">
        <div class="card-header">
          <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item"><a href="#contents1" class="nav-link active text-dark" data-toggle="tab">コミュニティ紹介</a></li>
            <li class="nav-item"><a href="#contents2" class="nav-link text-dark" data-toggle="tab">設定詳細</a></li>
          </ul>
        </div>
        <div class="row no-gutters">
          <div class="col-xl-4 col-lg-5 align-self-center sample-box">
            <%= image_tag @community.get_community_image(560, 560), class:"img-fluid d-block mx-auto p-1" %>
            <%= image_tag asset_path("stop_label.png"), size: "250x250", class:"d-block recruiting-stop" if @community.community_detail.recruiting_status == "closed" %>
          </div>
          <div class="col-xl-8 col-lg-7">
            <div class="tab-content">
              <div id="contents1" class="tab-pane active p-3">
                <div class="overflow-auto" style="height: 250px">
                  <p><%= safe_join(@community.introduction.split("\n"), tag(:br)) %></p>
                </div>
                <h6 class="text-secondary">設立日：<%= @community.created_at.strftime("%Y/%m/%d") %></h6>
                <h6><i class="fas fa-th-large mr-3"></i><span class="text-secondary"><%= @community.category.name if @community.category_id %></span></h6>
                <h6><i class="fas fa-tag mr-2"></i>
                  <% @community.tags.each do |community_tag| %>
                    <span class="text-secondary mr-1"><%= "#" + community_tag.name  %></span>
                  <% end %>
                </h6>
                <div class="d-flex justify-content-end">
                  <%= link_to '編集する', edit_admin_community_path(@community), class: "btn btn-info mr-2", style:"width: 30%" %>
                  <%= link_to '削除する', admin_community_path(@community), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger ml-2", style:"width: 30%" %>
                </div>
              </div>
              <div id="contents2" class="tab-pane p-3">
                <%= render 'admin/community_details/community_detail', detail: @community.community_detail %>
                <li><%= "募集ステータス：#{@community.community_detail.recruiting_status_i18n}" %></li>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-3">
    <%= render 'admin/communities/member', community: @community %>
  </div>

  <div class="d-flex justify-content-between mt-3">
    <h4>新着トピックス</h4>
    <%= link_to 'もっと見る>>', admin_community_topics_path(@community), class:"mt-2" %>
  </div>
  <div class="border mb-3"></div>
  <div class="table-responsive-xl overflow-auto", style="max-height:300px" >
    <table class="table text-nowrap">
      <thead class="thead-light sticky-top">
        <th>ID</th>
        <th>タイトル</th>
        <th>投稿者</th>
        <th>投稿日</th>
        <th>コミュニティ名</th>
        <th></th>
      </thead>
      <tbody>
        <%= render 'admin/topics/list', topics: @topics %>
      </tbody>
    </table>
  </div>

  <div class="text-center mx-auto mt-3">
    <%= link_to '質問・問い合わせページへ', question_admin_community_path(@community), class: "btn btn-outline-warning py-2", style:"width: 75%" %>
  </div>
</div>