config/routes.rb
Rails.application.routes.draw do
  # 会員用サインアップ・ログイン用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲスト用ログイン機能
  devise_scope :end_user do
    post "end_user/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "search" => "searches#search"
    resources :categories, only: [:show]
    resources :personal_tags, only: [:show]
    resources :tags, only: [:show]
    resources :notifications, only: [:index]

    # ユーザー関連
    resources "end_users", only: [:index, :show, :edit, :update] do
      resource "relationships", only: [:create, :destroy]
      get :following, on: :member
      get :follower, on: :member
      get :unsubscribe, on: :member
      patch :withdraw, on: :member
    end

    # コミュニティ関連
    resources "communities", except: [:destroy] do
      get :member, on: :member
      get :question, on: :member
      post :invitation
      resources "community_messages", only: [:new, :create, :destroy]
      resource "community_users", only: [:create, :destroy] do
        delete :evict
      end
      # トピック関連
      resources "topics", except: [:destroy] do
        resource "bookmarks", only: [:create, :destroy]
        resources "topic_comments", only: [:create, :destroy] do
          resource "goods", only: [:create, :destroy]
        end
      end
    end
  end

  # 管理者用サインアップ用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "homes/top", as: "home"
    get "topics/topic_list", as: "topics"
    get "topic_comments/topic_comment_list", as: "topic_comments"
    get "search" => "searches#search"
    resources "end_users", only: [:show, :edit, :update]
    resources "communities", only: [:index, :show, :edit, :update, :destroy] do
      get :member, on: :member
      get :question, on: :member
      resource "community_users", only: [:destroy]
      resources "community_messages", only: [:destroy]
      resources "topics", only: [:index, :show, :edit, :update, :destroy] do
        resources "topic_comments", only: [:update, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic_comment.rb
class TopicComment < ApplicationRecord
  belongs_to :end_user
  belongs_to :community
  belongs_to :topic
  has_many :goods, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :comment, presence: true, length: { maximum: 1000 }

  # コメントにいいねされているかの判定メソッド
  def good_by?(user)
    goods.exists?(end_user_id: user.id)
  end

  def self.search_for(content)
    TopicComment.where("comment Like?", "%#{content}%")
  end
end

app/controllers/admin/topic_comments_controller.rb
class Admin::TopicCommentsController < ApplicationController
  before_action :authenticate_admin!

  def topic_comment_list
    @topic_comments = TopicComment.all.order(id: "DESC").page(params[:page]).per(20)
  end

  def update
    topic_comment = TopicComment.find(params[:id])
    topic_comment.update(is_active: false)
    redirect_to request.referer, notice: "コメントを非表示にしました"
  end

  def destroy
    topic_comment = TopicComment.find(params[:id])
    topic_comment.destroy
    redirect_to request.referer, notice: "コメントを削除しました"
  end
end

app/helpers/admin/topic_comments_helper.rb
module Admin::TopicCommentsHelper
end

app/views/admin/topic_comments/_index.html.erb
<table class="table">
  <% topic_comments.each do |comment| %>
    <tr>
      <td>
        <% if comment.is_active %>
          <div class="row align-items-center mx-2">
            <div class="mr-2">
              <%= link_to admin_end_user_path(comment.end_user) do %>
                <%= image_tag comment.end_user.get_profile_image(50, 50), class:"d-block rounded-circle mx-auto" %>
              <% end %>
            </div>
            <div>
              <span class="text-info"><%= comment.end_user.nickname %></span><br>
              <small><%= comment.created_at.strftime("%Y/%m/%d\ %R") %></small>
            </div>
          </div>
          <div class="row content-body mx-4 mt-3">
            <%= comment.comment %>
          </div>
        <% else %>
          <div class="row mx-4 mt-3">
            <span>このコメントは管理者によって不適切と判定されました。</span>
          </div>
        <% end %>
        <div class="row justify-content-end align-items-center mx-2">
          <small class="mx-2"><i class="far fa-heart"></i>&nbsp;<%= comment.goods.count %></small>
        </div>
      </td>
      <td class="col-1 align-middle">
        <div class="dropdown">
          <button type="button" id="dropdown-<%=comment.id %>" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">メニュー</button>
          <div class="dropdown-menu" aria-labelledby="dropdown-<%=comment.id %>">
            <%= link_to '非表示', admin_community_topic_topic_comment_path(comment.topic.community,comment.topic,comment), method: :patch, data: {confirm: "非表示にしますか？"}, class:"dropdown-item" if comment.is_active %>
            <%= link_to '削除', admin_community_topic_topic_comment_path(comment.topic.community,comment.topic,comment), method: :delete, data: {confirm: "削除しますか？"}, class:"dropdown-item" %>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/topic_comments/_list.html.erb
<% topic_comments.each do |comment| %>
  <tr>
    <td><%= comment.id %></td>
    <td><%= comment.comment.truncate(25) %></td>
    <td><%= link_to comment.end_user.nickname, admin_end_user_path(comment.end_user) %></td>
    <td><%= comment.created_at.strftime("%Y/%m/%d\ %R") %></td>
    <td>
      <% if comment.is_active? %>
        <span class="text-success">有効</span>
      <% else %>
        <span class="text-danger">非表示</span>
      <% end %>
    </td>
    <td>
      <div class="dropdown">
        <button type="button" id="dropdown-<%=comment.id %>" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">メニュー</button>
        <div class="dropdown-menu" aria-labelledby="dropdown-<%=comment.id %>">
          <%= link_to "詳細", admin_community_topic_path(comment.topic.community, comment.topic), class: "dropdown-item" %>
          <%= link_to '非表示', admin_community_topic_topic_comment_path(comment.topic.community,comment.topic,comment), method: :patch, data: {confirm: "非表示にしますか？"}, class:"dropdown-item" if comment.is_active %>
          <%= link_to '削除', admin_community_topic_topic_comment_path(comment.topic.community,comment.topic,comment), method: :delete, data: {confirm: "削除しますか？"}, class:"dropdown-item" %>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/admin/topic_comments/topic_comment_list.html.erb
<div class="container py-5">
  <div class="row justify-content-end">
    <div class="col-lg-6 col-md-8 col-sm-12">
      <%= render 'admin/searches/form' %>
    </div>
  </div>
  <div class="row m-4">
    <h3>コメント一覧</h3>
  </div>
  <div class="table-responsive-xl">
    <table class="table text-nowrap">
      <thead class="thead-light">
        <th>CommentID</th>
        <th>コメント</th>
        <th>投稿者</th>
        <th>投稿日</th>
        <th>表示</th>
        <th></th>
      </thead>
      <tbody>
        <%= render 'admin/topic_comments/list', topic_comments: @topic_comments %>
      </tbody>
    </table>
  </div>
  <%= paginate @topic_comments %>
</div>