config/routes.rb
Rails.application.routes.draw do
  # 会員用サインアップ・ログイン用
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲスト用ログイン機能
  devise_scope :end_user do
    post "end_user/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about"
    get "search" => "searches#search"
    resources :categories, only: [:show]
    resources :personal_tags, only: [:show]
    resources :tags, only: [:show]
    resources :notifications, only: [:index]

    # ユーザー関連
    resources "end_users", only: [:index, :show, :edit, :update] do
      resource "relationships", only: [:create, :destroy]
      get :following, on: :member
      get :follower, on: :member
      get :unsubscribe, on: :member
      patch :withdraw, on: :member
    end

    # コミュニティ関連
    resources "communities", except: [:destroy] do
      get :member, on: :member
      get :question, on: :member
      post :invitation
      resources "community_messages", only: [:new, :create, :destroy]
      resource "community_users", only: [:create, :destroy] do
        delete :evict
      end
      # トピック関連
      resources "topics", except: [:destroy] do
        resource "bookmarks", only: [:create, :destroy]
        resources "topic_comments", only: [:create, :destroy] do
          resource "goods", only: [:create, :destroy]
        end
      end
    end
  end

  # 管理者用サインアップ用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get "homes/top", as: "home"
    get "topics/topic_list", as: "topics"
    get "topic_comments/topic_comment_list", as: "topic_comments"
    get "search" => "searches#search"
    resources "end_users", only: [:show, :edit, :update]
    resources "communities", only: [:index, :show, :edit, :update, :destroy] do
      get :member, on: :member
      get :question, on: :member
      resource "community_users", only: [:destroy]
      resources "community_messages", only: [:destroy]
      resources "topics", only: [:index, :show, :edit, :update, :destroy] do
        resources "topic_comments", only: [:update, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %>件のエラーがあります</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li class="text-danger my-2"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "alert" %>
    <div class="alert alert-danger text-center"><%= message %></div>
  <% elsif message_type == "notice" %>
    <div class="alert alert-success text-center"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
  <div class="container py-4">
    <p class="text-muted text-center">&copy; 2022 Circle</p>
  </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white p-2">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="<%= asset_path("logo.png")%>" width="100" height="45" class="d-inline-block align-top" alt="Logo">
    </a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse"  id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item mx-2 my-1 px-2">
            <%= link_to "ユーザー一覧", admin_home_path, class:'nav-link text-secondary' %>
          </li>
          <li class="nav-item mx-2 my-1 px-2">
            <%= link_to "コミュニティ一覧", admin_communities_path, class:'nav-link text-secondary' %>
          </li>
          <li class="nav-item mx-2 my-1 px-2">
            <%= link_to "トピックス一覧", admin_topics_path, class:'nav-link text-secondary' %>
          </li>
          <li class="nav-item mx-2 my-1 px-2">
            <%= link_to "コメント一覧", admin_topic_comments_path, class:'nav-link text-secondary' %>
          </li>
          <li class="nav-item mx-2 my-1 px-2">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'nav-link text-secondary' %>
          </li>
        <% elsif end_user_signed_in? %>
          <li class="nav-item mx-2 my-1 px-2">
            <%= link_to "コミュニティを探す", communities_path, class:'nav-link text-secondary' %>
          </li>
          <li class="nav-item mx-2 my-1 px-2">
            <%= link_to "ユーザーを探す", end_users_path, class:'nav-link text-secondary' %>
          </li>
          <li class="nav-item rounded-pill bg-warning mx-2 my-1 px-2">
            <%= link_to "マイページ", end_user_path(current_end_user), class:'nav-link text-light' %>
          </li>
          <li class="border border-warning rounded-pill mx-2 my-1 px-2">
            <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class:'nav-link text-warning' %>
          </li>
        <% else %>
          <li class="nav-item mx-2 my-1 px-4">
            <%= link_to "利用方法", about_path, class:'nav-link text-secondary' %>
          </li>
          <li class="rounded-pill bg-warning mx-2 my-1 px-4">
            <%= link_to "新規登録", new_end_user_registration_path, class:'nav-link text-light' %>
          </li>
          <li class="border border-warning rounded-pill mx-2 my-1 px-4">
            <%= link_to "ログイン", new_end_user_session_path, class:'nav-link text-warning' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <%= render "layouts/header" %>
    </header>
    <main class="site-thema">
      <div id="flash-message">
        <%= render 'layouts/flash_message' %>
      </div>
      <%= yield %>
      <span id="back">
        <a href="#"><img src="<%= asset_path("arrow.png") %>" alt=""></a>
      </span>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
    <%= javascript_pack_tag "script.js" %>
  </body>
</html>